Bot school
uchoamp/consuchat-bot pull request #6
Opened 2023-11-11 16:49 UTC by uchoamp

2023-11-11 17:03 UTC, uchoamp commented on src/presentation/conversations/new-user-conversation.ts
Essa alteração provavelmente vai gerar um bug, na verdade não entendi muito em

2023-11-11 17:13 UTC, pachecoum requested changes
Remover pedaços de códigos comentados

2023-11-15 16:22 UTC, AlanManoel approved these changes

2023-11-18 22:02 UTC, pachecoum approved these changes

2023-11-18 22:03 UTC, merged